openapi: 3.0.1
info:
  title: Access Token
  description: 'Access Tokens are required to execute all API actions, you can use this resource to obtain one. The authority of the bearer token; the actions it can execute, is determined by the associated Merchant ID, Accounts and Permissions of the app used to create it.'
  contact:
    name: API Integrations
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: api.integrations@globalpay.com
  version: 2020 10 22
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
tags:
  - name: Create Access Token
    description: Authenticate using app credentials to use GP API.
    externalDocs:
      url: 'https://developer.globalpay.com/authentication'
paths:
  /accesstoken:
    post:
      operationId: getAccessToken
      tags:
        - Create Access Token
      summary: Create a bearer access token.
      description: 'Using your app credentials, send a request to create a bearer access token that can be used to execute subsequent API actions. The actions  that the token can execute are determined by the permissions the app has. For more information on API authentication and creating access  tokens'
      parameters:
        - $ref: ./models/common2.v1.yaml#/components/parameters/header_Content-type
        - $ref: ./models/common2.v1.yaml#/components/parameters/header_X-GP-Version
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request'
        required: false
      responses:
        '200':
          description: OK
          headers:
            Content-type:
              description: Format of the message.
              schema:
                type: string
                default: application/json
            X-GP-Version:
              description: Indicates the version of the GP-API for this message.
              schema:
                type: string
                default: '2020-10-22'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '400':
          $ref: errors.yaml#/components/responses/RequestInvalid_400
        '401':
          $ref: errors.yaml#/components/responses/AuthenticationInvalid_401
        '403':
          $ref: errors.yaml#/components/responses/NotAuthorized_403
        '404':
          description: Resource Not Found
          content: {}
        '500':
          $ref: errors.yaml#/components/responses/ServerError_500
        '501':
          $ref: errors.yaml#/components/responses/UnknownServerError_501
        '502':
          $ref: errors.yaml#/components/responses/UnknownPlatformError_502
        '504':
          $ref: errors.yaml#/components/responses/ServerTimeout_504
        x-codegen-request-body-name: request
      
components:
  schemas:
    request:
      required:
        - app_id
        - grant_type
        - nonce
        - secret
      type: object
      properties:
        app_id:
          $ref: ./models/common2.v1.yaml#/components/schemas/app_id
        nonce:
          $ref: ./models/common2.v1.yaml#/components/schemas/nonce
        secret:
          $ref: ./models/common2.v1.yaml#/components/schemas/secret
        grant_type:
         $ref: ./models/common2.v1.yaml#/components/schemas/grant_type
        seconds_to_expire:
         $ref: ./models/common2.v1.yaml#/components/schemas/seconds_to_expire
        interval_to_expire:
          $ref: ./models/common2.v1.yaml#/components/schemas/interval_to_expire
        permissions:
         $ref: ./models/common2.v1.yaml#/components/schemas/permissions
    
    response:
      type: object
      properties:
        token:
          $ref: ./models/common2.v1.yaml#/components/schemas/token
        type:
          type: string
          description: The type of token created.
          example: Bearer
        scope:
          $ref: '#/components/schemas/scope'
        app_id:
          type: string
          description: The app id that was used to create the token.
          example: i9R0byBBor6RqTQNj3g4MuVBwH5rd7yR
          minLength: 1
          maxLength: 50
        app_name:
          type: string
          description: The name of the app the user gave to the application.
          example: demo_app
          minLength: 1
          maxLength: 50
        time_created:
          type: string
          format: date-time
          description: Global Payments time indicating when the token was created.
          example: '2020-05-03T21:23:39.718Z'
        seconds_to_expire:
          type: number
          description: |
            The time left in seconds before the token will expire.
          example: 604799
          maximum: 604799
        interval_to_expire:
          type: string
          description: |
            The time interval set for when the token will expire.
          example: 1_HOUR
          enum:
            - WEEK
            - DAY
            - 12_HOURS
            - 6_HOURS
            - 3_HOURS
            - 1_HOUR
            - 30_MINUTES
            - 10_MINUTES
            - 5_MINUTES
        email:
          type: string
          description: 'Email registered with the application that was used to access this token. '
          example: james.mason@example.com
          minLength: 1
          maxLength: 50
    scope:
      type: object
      properties:
        merchant_id:
          type: string
          description: A unique identifier for the merchant set by Global Payments.
          example: MER_c4c0df11039c48a9b63701adeaa296c3
          minLength: 1
          maxLength: 50
        merchant_name:
          type: string
          description: A meaningful label for the merchant set by Global Payments.
          example: Sandbox_merchant_2
          minLength: 1
          maxLength: 50
        accounts:
          $ref: '#/components/schemas/accounts'
    accounts:
      type: array
      items:
        type: object
        properties:
          account_id:
            type: string
            description: A unique identifier for the merchant account set by Global Payments.
            example: TRA_6716058969854a48b33347043ff8225f
            minLength: 1
            maxLength: 50
          account_name:
            type: string
            description: A meaningful label for the merchant account set by Global Payments.
            example: Transaction_Processing
            minLength: 1
            maxLength: 50
          permissions:
            type: array
            items:
              type: string
              description: 'The list of the permissions the token has authority to execute via the API. Each permission indicates a Resource, HTTP Verb and Action the token can execute.'
              example: 'TRN_POST_AUTHORIZE, TRN_POST_CAPTURE'
