openapi: 3.0.1

info:
  title: Deposits  
  description: Deposits represent the initiation of a Debit or a Credit to a Merchant's Bank Account that relates to Transactions and Disputes processed, or fees charged to the Merchant.
  contact:
    name: 'API Integrations'
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: 'api.integrations@globalpay.com'
  version: '2020 10 22'
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
tags:
  - name: Get a list of Deposit information
    description:  Get information about the amounts Global Payments affected to merchant's bank account(s).
    externalDocs:
      url: 'https://developer.globalpay.com/settlement-reporting/step-by-step-guide'    
  - name: Get a Single Deposit
    description: Get information about a single amount Global Payments affected to merchant's bank account.
    externalDocs:
      url: 'https://developer.globalpay.com/settlement-reporting/step-by-step-guide'      
      

paths:
  /settlement/deposits:
    get:
      operationId: getDepositList
      tags:
      - Get a list of Deposit information
      summary: Get a list of Deposits using criteria passed in the query string. Page through the result set to access all records.
      description: Get a list of Deposits using criteria passed in the query string. Page through the result set to access all records.
      
      parameters:
      
      - name: Authorization
        in: header
        description: The Bearer token used when executing this action.
        required: true
        schema:
          type: string
          example: 'Bearer MECaTYne0ch1VX2byAPZiJHhq6bc'
          minLength: 1
          maxLength: 50
      
      - $ref: ./models/common2.v1.yaml#/components/parameters/header_X-GP-Version
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_page
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_page_size
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_order
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_order_by
      
      
      - name: account_name
        in: query
        required: true
        example: 'settlement_reporting'
        schema:
          $ref: ./models/common2.v1.yaml#/components/schemas/account_name
      
      - name: from_time_created
        in: query
        schema:
          $ref: ./models/common2.v1.yaml#/components/schemas/from_time_created
      
      - name: to_time_created
        in: query
        schema:
          $ref: ./models/common2.v1.yaml#/components/schemas/to_time_created
      
      - name: id
        in: query
        schema:
          $ref: ./models/common2.v1.yaml#/components/schemas/id

      - name: status
        in: query
        schema:
          $ref: ./models/common2.v1.yaml#/components/schemas/status

      
      - name: amount
        in: query
        schema:
          $ref: ./models/common2.v1.yaml#/components/schemas/deposit.amount
      
   
      - name: masked_account_number_last4
        in: query
        schema:
           $ref: ./models/common2.v1.yaml#/components/schemas/masked_account_number_last4

      - name: system.mid
        in: query
        schema:
           $ref: ./models/common2.v1.yaml#/components/schemas/system.mid

      - name: system.hierarchy
        in: query
        schema:
          $ref: ./models/common2.v1.yaml#/components/schemas/system.hierarchy

      responses:
        '200':
          description: OK
          headers:
            Content-type:
              $ref: ./models/common2.v1.yaml#/components/parameters/header_Content-type
            X-GP-Version:
              $ref: ./models/common2.v1.yaml#/components/parameters/header_X-GP-Version
            Content-Encoding:
               $ref: ./models/common2.v1.yaml#/components/parameters/header_Content-Encoding
          
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deposits_list'
       
        '400':
          $ref: ./models/errors.yaml#/components/responses/RequestInvalid_400
        '401':
          $ref: ./models/errors.yaml#/components/responses/AuthenticationInvalid_401
        '403':
          $ref: ./models/errors.yaml#/components/responses/NotAuthorized_403
        '404':
          description: Resource Not Found
          content: {}
        '500':
          $ref: ./models/errors.yaml#/components/responses/ServerError_500
        '501':
          $ref: ./models/errors.yaml#/components/responses/UnknownServerError_501
        '502':
          $ref: ./models/errors.yaml#/components/responses/UnknownPlatformError_502
        '504':
          $ref: ./models/errors.yaml#/components/responses/ServerTimeout_504
        x-codegen-request-body-name: request

  /settlement/deposits/{id}:
    get:
      operationId: getDepositSingle
      tags:
      - Get a Single Deposit
      summary: Get the details of a single Deposit using its unique id.
      description: Get the details of a single Deposit using its unique id.
      parameters:
      - name: Authorization
        in: header
        description: The Bearer token used when executing this action.
        required: true
        schema:
          type: string
          example: Bearer MECaTYne0ch1VX2byAPZiJHhq6bc
          minLength: 1
          maxLength: 50
      
      - $ref: ./models/common2.v1.yaml#/components/parameters/header_X-GP-Version
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_page
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_page_size
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_order
      - $ref: ./models/common2.v1.yaml#/components/parameters/query_pagination_order_by
      
      - name: id
        in: path
        description: This is the deposit id created to uniquely identify it in the Global Payments system. 
        required: true
        schema:
         $ref: ./models/common2.v1.yaml#/components/schemas/id

      responses:
         '200':
          description: OK
          headers:
            Content-type:
              $ref: ./models/common2.v1.yaml#/components/parameters/header_Content-type
            X-GP-Version:
              $ref: ./models/common2.v1.yaml#/components/parameters/header_X-GP-Version
            Content-Encoding:
               $ref: ./models/common2.v1.yaml#/components/parameters/header_Content-Encoding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deposits_single'
       
          '400':
            $ref: ./models/errors.yaml#/components/responses/RequestInvalid_400
          '401':
            $ref: ./models/errors.yaml#/components/responses/AuthenticationInvalid_401
          '403':
            $ref: ./models/errors.yaml#/components/responses/NotAuthorized_403
          '404':
            description: Resource Not Found
            content: {}
          '500':
            $ref: ./models/errors.yaml#/components/responses/ServerError_500
          '501':
            $ref: ./models/errors.yaml#/components/responses/UnknownServerError_501
          '502':
            $ref: ./models/errors.yaml#/components/responses/UnknownPlatformError_502
          '504':
            $ref: ./models/errors.yaml#/components/responses/ServerTimeout_504
          x-codegen-request-body-name: request

                
        
components:
  schemas:
    
    deposits_list:
      type: object
      properties:
        total_record_count:
          $ref: ./models/common2.v1.yaml#/components/schemas/pagination.total_record_count
        current_page_size:
          $ref: ./models/common2.v1.yaml#/components/schemas/pagination.current_page_size
        merchant_id:
          $ref: ./models/common2.v1.yaml#/components/schemas/merchant_id
        merchant_name:
          $ref: ./models/common2.v1.yaml#/components/schemas/merchant_name
        account_id:
          $ref: ./models/common2.v1.yaml#/components/schemas/account_id
        account_name:
          $ref: ./models/common2.v1.yaml#/components/schemas/account_name
        filter:
          $ref: ./models/common2.v1.yaml#/components/schemas/filter
        paging:
          $ref: ./models/common2.v1.yaml#/components/schemas/paging
        deposits:
          type: array
          description: A list of Deposit records.
          items:
            $ref: '#/components/schemas/deposits_single'
        action:
          $ref: ./models/common2.v1.yaml#/components/schemas/action
    
    deposits_single:
      type: object
      properties:
        id:
          $ref: ./models/common2.v1.yaml#/components/schemas/id
        time_created:
          $ref: ./models/common2.v1.yaml#/components/schemas/time_created
        status:
          $ref: ./models/common2.v1.yaml#/components/schemas/status
        funding_type:
          $ref: ./models/common2.v1.yaml#/components/schemas/funding_type
        amount:
          $ref: ./models/common2.v1.yaml#/components/schemas/deposit.amount
        aggregation_model:
          $ref: ./models/common2.v1.yaml#/components/schemas/aggregation_model
        bank_transfer:
          $ref: ./models/common2.v1.yaml#/components/schemas/bank_transfer
        system:
          $ref: ./models/common2.v1.yaml#/components/schemas/system
        sales:
          $ref: ./models/common2.v1.yaml#/components/schemas/totals
        refunds:
          $ref: ./models/common2.v1.yaml#/components/schemas/totals
        disputes:
          type: object
          description: Data relating to the dispute totals across chargebacks and chargeback reversals.
          properties:
            chargebacks:
              $ref: ./models/common2.v1.yaml#/components/schemas/totals
            reversals:
              $ref: ./models/common2.v1.yaml#/components/schemas/totals
          
        discounts:
          $ref: ./models/common2.v1.yaml#/components/schemas/totals
        fees:
          type: object
          description: The total fees amount in the currency of the Deposit.
          properties:
            amount:
              $ref: ./models/common2.v1.yaml#/components/schemas/total_amount
          
        action:
          $ref: ./models/common2.v1.yaml#/components/schemas/action
    