openapi: '3.0.3'

info:
  title: Accounts  
  description: Accounts represent the payment processing capability a merchant has configured on the Global Payments API.
  contact:
    name: 'API Integrations'
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: 'api.integrations@globalpay.com'
  version: '2020 12 22'
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
tags:
  - name: Get Merchant info
    description: Get information about the merchant executing the action.

  - name: Get Merchants Account info
    description: Get information about the merchant's account configurations.
  
  - name: Get Single Account info
    description: Get information about a merchant's single account configuration.
  
      
          

paths:
  /:
    get:
      operationId: getMerchantSingle
      tags:
      - Get Merchant info
      summary: Get information about the merchant executing the action.
      description: Get information about the merchant executing the action.
      
      parameters:
      
      - $ref: ./models/parameters.v1.yaml#/components/parameters/header_Authorization      
      - $ref: ./models/parameters.v1.yaml#/components/parameters/header_X-GP-Version     

      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Type      
            Content-Encoding:  
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Encoding
            X-GP-Version:  
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/X-GP-Version
                
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/merchants_single'
       
        '400':
          $ref: ./models/errors.yaml#/components/responses/RequestInvalid_400
        '401':
          $ref: ./models/errors.yaml#/components/responses/AuthenticationInvalid_401
        '403':
          $ref: ./models/errors.yaml#/components/responses/NotAuthorized_403
        '404':
          description: Resource Not Found
          content: {}
        '500':
          $ref: ./models/errors.yaml#/components/responses/ServerError_500
        '501':
          $ref: ./models/errors.yaml#/components/responses/UnknownServerError_501
        '502':
          $ref: ./models/errors.yaml#/components/responses/UnknownPlatformError_502
        '504':
          $ref: ./models/errors.yaml#/components/responses/ServerTimeout_504
    
  /accounts:
    get:
      operationId: getMerchantAccounts
      tags:
      - Get Merchants Account info
      summary: Get information about the merchant's accounts.
      description: Get information about the merchant's accounts.
      
      parameters:
      
      - $ref: ./models/parameters.v1.yaml#/components/parameters/header_Authorization      
      - $ref: ./models/parameters.v1.yaml#/components/parameters/header_X-GP-Version     

      - name: status
        in: query
        schema:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/status

      - name: name
        in: query
        schema:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/account_name
      
      - name: id
        in: query
        schema:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/id

      - name: from_time_created
        in: query
        schema:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/from_time_created
      
      - name: to_time_created
        in: query
        schema:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/to_time_created
      
      
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Type      
            Content-Encoding:  
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Encoding
            X-GP-Version:  
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/X-GP-Version
                
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts_list'
       
        '400':
          $ref: ./models/errors.yaml#/components/responses/RequestInvalid_400
        '401':
          $ref: ./models/errors.yaml#/components/responses/AuthenticationInvalid_401
        '403':
          $ref: ./models/errors.yaml#/components/responses/NotAuthorized_403
        '404':
          description: Resource Not Found
          content: {}
        '500':
          $ref: ./models/errors.yaml#/components/responses/ServerError_500
        '501':
          $ref: ./models/errors.yaml#/components/responses/UnknownServerError_501
        '502':
          $ref: ./models/errors.yaml#/components/responses/UnknownPlatformError_502
        '504':
          $ref: ./models/errors.yaml#/components/responses/ServerTimeout_504
    

  /accounts/{id}:
    get:
      operationId: getAccountSingle
      tags:
      - Get a Single Account
      summary: Get the details of a single Account using its unique id.
      description: Get the details of a single Account using its unique id.
      parameters:
      - $ref: ./models/parameters.v1.yaml#/components/parameters/header_Authorization
      
      - $ref: ./models/parameters.v1.yaml#/components/parameters/header_X-GP-Version
      
      
      - name: id
        in: path
        description: This is the account id created to uniquely identify it in the Global Payments system. 
        required: true
        schema:
         $ref: ./models/data_dictionary.v1.yaml#/components/schemas/id

      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Type      
            Content-Encoding:  
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Encoding
            X-GP-Version:  
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/X-GP-Version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts_single'
       
        '400':
          $ref: ./models/errors.yaml#/components/responses/RequestInvalid_400
        '401':
          $ref: ./models/errors.yaml#/components/responses/AuthenticationInvalid_401
        '403':
          $ref: ./models/errors.yaml#/components/responses/NotAuthorized_403
        '404':
          description: Resource Not Found
          content: {}
        '500':
          $ref: ./models/errors.yaml#/components/responses/ServerError_500
        '501':
          $ref: ./models/errors.yaml#/components/responses/UnknownServerError_501
        '502':
          $ref: ./models/errors.yaml#/components/responses/UnknownPlatformError_502
        '504':
          $ref: ./models/errors.yaml#/components/responses/ServerTimeout_504
  
                
        
components:
  schemas:
    merchants_single:
      type: object
      properties:
        id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant_id
        merchant_name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant_name
        time_created:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/time_created
        status:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant.status
        email:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant.email
        address_1:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/address.line_1
        address_2:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/address.line_2
        city:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/address.city
        zip:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/address.postal_code
        state:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/address.state
        country:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/address.country


        links:
          type: array
          items:
            $ref: ./models/schema_objects.v1.yaml#/components/schemas/links

        action:
          $ref: ./models/schema_objects.v1.yaml#/components/schemas/action

    accounts_list:
      type: object
      properties:
        total_record_count:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/pagination.total_record_count
        current_page_size:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/pagination.current_page_size
        merchant_id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant_id
        merchant_name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant_name
       
        filter:
          $ref: ./models/schema_objects.v1.yaml#/components/schemas/filter
        paging:
          $ref: ./models/schema_objects.v1.yaml#/components/schemas/paging
        acounts:
          type: array
          description: A list of Account records.
          items:
            $ref: '#/components/schemas/accounts_single'
        action:
          $ref: ./models/schema_objects.v1.yaml#/components/schemas/action
    
    accounts_single:
      type: object
      properties:
        id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/id
        type:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/account.type
        name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/account_name
        status:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/entity.status
        permissions:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/account.permissions
          
        action:
          $ref: ./models/schema_objects.v1.yaml#/components/schemas/action

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer 
      
security:
  - bearerAuth: []        
