openapi: 3.0.3
info:
  title: Verifications
  description: Verifications represent the validation of a payment method to ensure it can be used in the creation of a Transaction.
  contact:
    name: API Integrations
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: api.integrations@globalpay.com
  version: 2020 12 22
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
tags:
  - name: Verify
    description: Verify a payment method to ensure it can be used to create a Transaction at a later time.
paths:
  /verifications:
    post:
      operationId: createVerification
      tags:
        - Verify
      description: Verify a payment method to ensure it can be used to create a Transaction at a later time.
      parameters:
        - $ref: ./models/parameters.v1.yaml#/components/parameters/header_X-GP-Version
        - $ref: ./models/parameters.v1.yaml#/components/parameters/header_Authorization
        - $ref: ./models/parameters.v1.yaml#/components/parameters/header_X-GP-Idempotency
        - $ref: ./models/parameters.v1.yaml#/components/parameters/header_Content-Type
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_request'
            examples:
              Verify a Card:
                $ref: ./models/examples.v1.yaml#/components/examples/verification_request
        required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Type
            Content-Encoding:
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/Content-Encoding
            X-GP-Idempotency:
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/X-GP-Idempotency
            X-GP-Version:
              schema:
                $ref: ./models/data_dictionary.v1.yaml#/components/schemas/X-GP-Version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create_response'
        '400':
          $ref: ./models/errors.yaml#/components/responses/RequestInvalid_400
        '401':
          $ref: ./models/errors.yaml#/components/responses/AuthenticationInvalid_401
        '403':
          $ref: ./models/errors.yaml#/components/responses/NotAuthorized_403
        '404':
          description: Resource Not Found
          content: {}
        '500':
          $ref: ./models/errors.yaml#/components/responses/ServerError_500
        '501':
          $ref: ./models/errors.yaml#/components/responses/UnknownServerError_501
        '502':
          $ref: ./models/errors.yaml#/components/responses/UnknownPlatformError_502
        '504':
          $ref: ./models/errors.yaml#/components/responses/ServerTimeout_504
components:
  schemas:
    create_request:
      required:
        - account_name
        - channel
        - currency
        - country
        - payment_method
        - reference
      type: object
      properties:
        account_name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/account_name
        channel:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/transaction.channel
        currency:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/currency
        reference:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/transaction.reference
        country:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/country
        payment_method:
          $ref: '#/components/schemas/payment_method_request'
    create_response:
      type: object
      properties:
        id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/verification.id
        time_created:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/time_created
        status:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/verification.status
        channel:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/transaction.channel
        currency:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/currency
        country:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/country
        merchant_id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant_id
        merchant_name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/merchant_name
        account_id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/account_id
        account_name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/account_name
        reference:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/transaction.reference
        payment_method:
          $ref: '#/components/schemas/payment_method_response'
        action:
          $ref: ./models/schema_objects.v1.yaml#/components/schemas/action
    payment_method_request:
      type: object
      properties:
        id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.id
        first_name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.first_name
        last_name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.last_name
        name:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.name
        entry_mode:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.entry_mode
        encryption:
          $ref: ./models/schema_objects.v1.yaml#/components/schemas/encryption
        card:
          $ref: '#/components/schemas/card_request'
    payment_method_response:
      type: object
      properties:
        id:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.id
        result:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.result
        message:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.message
        entry_mode:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/payment_method.entry_mode
        card:
          $ref: '#/components/schemas/card_response'
    card_request:
      type: object
      properties:
        number:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.number
        expiry_month:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.expiry_month
        expiry_year:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.expiry_year
        track:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.track
        cvv:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.cvv
        cvv_indicator:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.cvv_indicator
        avs_address:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.avs_address
        avs_postal_code:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.avs_postal_code
    card_response:
      type: object
      properties:
        masked_number_last4:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.masked_number_last4
        brand:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.brand
        brand_reference:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.brand_reference
        cvv_result:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.cvv_result
        avs_address_result:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.avs_address_result
        avs_postal_code_result:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.avs_postal_code_result
        avs_action:
          $ref: ./models/data_dictionary.v1.yaml#/components/schemas/card.avs_action
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
