openapi: '3.0.0'
info:
  title: Common Object Schema
  contact:
    name: API Integrations
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: api.integrations@globalpay.com
  version: 2020 10 22
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
paths: {}
components:
  schemas: ## Schema Section - Objects

    encryption:
      type: object
      properties:
        method:
          $ref: data_dictionary.v1.yaml#/components/schemas/encryption.method
        version:
          $ref: data_dictionary.v1.yaml#/components/schemas/encryption.version
        info:
         $ref: data_dictionary.v1.yaml#/components/schemas/encryption.info

    order:
      type: object
      description: The information relating to an order. An order can be fulfilled by multiple transactions.
      properties:
        reference:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/order.reference'

    authentication:
      type: object
      description: Information outlining the degree of authentication executed related to a transaction.
      properties:
        three_ds:
          $ref: '#/components/schemas/three_ds'
    
    three_ds:
      type: object
      description: Information outlining the degree of 3D Secure authentication executed.
      properties:
        message_version:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.message_version
        eci:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.eci
        value:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.value
        server_trans_ref:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.server_trans_ref
        ds_trans_ref:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.ds_trans_ref

    authentication_response:
      type: object
      description: Information outlining the degree of authentication executed related to a transaction.
      properties:
        three_ds:
          $ref: '#/components/schemas/three_ds_response'
    
    three_ds_response:
      type: object
      description: Information outlining the degree of 3D Secure authentication executed.
      properties:
        value_result:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.value_result

    stored_credential:
      type: object
      description: Stored data information used to create a transaction.
      properties:
        model:
          $ref: data_dictionary.v1.yaml#/components/schemas/stored_credential.model  
        reason:
          $ref: data_dictionary.v1.yaml#/components/schemas/stored_credential.reason
        sequence:
          $ref: data_dictionary.v1.yaml#/components/schemas/stored_credential.sequence

    totals:
      type: object
      description: The total number of records and the total amount across those records.
      properties:
        count:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/count'
        amount:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/total_amount'
      
    bank_transfer:
      type: object
      properties:
        masked_account_number_last4:
          type: string
          description: The last 4 characters of the local reference for a bank account
            number.
        bank:
          $ref: '#/components/schemas/bank'
      description: Data relating to a bank transfer directly to or from the Payer's bank account.
    
    bank:
      type: object
      properties:
        code:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/bank.code'

    bank_account:
      type: object
      properties:
        name:
          type: string
          description: The name assocaited with the bank account
        identifier_code:
          type: string
          description: The international identifier code for the bank.
        iban:
          type: string
          description: The international identifier of the bank account.
        code:
          type: string
          description: The local identifier of the bank.
        account_number:
          type: string
          description: The local identifier of the bank account.
   
    mandate:
      type: object
      properties:
        code:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/apm.mandate.reference'
    
    filter:
      type: object
      description: Indicates what fields and values used to filter the current list of resource objects in the current response.
    
    paging:
      type: object
      description: The paging values used to generate this response.
      properties:
        page:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.page'
        page_size:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.page_size'
        order_by:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.order_by'
        order:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.order'
     
    scope:
      type: object
      properties:
        merchant_id:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/merchant_id'
        merchant_name:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/merchant_name'
        accounts:
          $ref: '#/components/schemas/accounts'
    
    accounts:
      type: array
      items:
        type: object
        properties:
          account_id:
            $ref: 'data_dictionary.v1.yaml#/components/schemas/account_id'
          account_name:
            $ref: 'data_dictionary.v1.yaml#/components/schemas/account_name'
          permissions:
            type: array
            items:
              $ref: 'data_dictionary.v1.yaml#/components/schemas/permissions'
    system:
      type: object
      description: Configuration relating to a transactions from the Global Payments system. This info is relevant for troubleshooting and integrators using other Global Payments systems to payment process.
      properties:
        mid:
           $ref: 'data_dictionary.v1.yaml#/components/schemas/system.mid'
        tid:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.tid'
        hierarchy:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.hierarchy'
        name:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.name'
        dba:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.dba'

    action:
      type: object
      description: Information about the Action executed.
      properties:
        id:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/id'
        type:
          type: string
          description: Indicates the action taken.
          example: DEPOSIT_LIST
          enum: ##REVISIT##
          - DEPOSIT_LIST
          - DEPOSIT_SINGLE
        time_created:
           $ref: 'data_dictionary.v1.yaml#/components/schemas/time_created'
        result_code:
           $ref: 'data_dictionary.v1.yaml#/components/schemas/result_code'
        app_id:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/app_id'
        app_name:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/app_name'
 
## Security Section
  securitySchemes:  ## Security Section
    bearerAuth:
      type: http
      scheme: bearer
