openapi: '3.0.3'
info:
  title: Common Object Schema
  contact:
    name: API Integrations
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: api.integrations@globalpay.com
  version: 2020 10 22
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
paths: {}
components:
  schemas: ## Schema Section - Objects

    encryption:
      type: object
      properties:
        method:
          $ref: data_dictionary.v1.yaml#/components/schemas/encryption.method
        version:
          $ref: data_dictionary.v1.yaml#/components/schemas/encryption.version
        info:
         $ref: data_dictionary.v1.yaml#/components/schemas/encryption.info

    order:
      type: object
      description: The information relating to an order. An order can be fulfilled by multiple transactions.
      properties:
        reference:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/order.reference'

    authentication:
      type: object
      description: Information outlining the degree of authentication executed related to a transaction.
      properties:
        three_ds:
          $ref: '#/components/schemas/three_ds'
    
    three_ds:
      type: object
      description: Information outlining the degree of 3D Secure authentication executed.
      properties:
        message_version:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.message_version
        eci:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.eci
        value:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.value
        server_trans_ref:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.server_trans_ref
        ds_trans_ref:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.ds_trans_ref

    authentication_response:
      type: object
      description: Information outlining the degree of authentication executed related to a transaction.
      properties:
        three_ds:
          $ref: '#/components/schemas/three_ds_response'
    
    three_ds_response:
      type: object
      description: Information outlining the degree of 3D Secure authentication executed.
      properties:
        value_result:
          $ref: data_dictionary.v1.yaml#/components/schemas/three_ds.value_result

    stored_credential:
      type: object
      description: Stored data information used to create a transaction.
      properties:
        model:
          $ref: data_dictionary.v1.yaml#/components/schemas/stored_credential.model  
        reason:
          $ref: data_dictionary.v1.yaml#/components/schemas/stored_credential.reason
        sequence:
          $ref: data_dictionary.v1.yaml#/components/schemas/stored_credential.sequence

    totals:
      type: object
      description: The total number of records and the total amount across those records.
      properties:
        count:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/count'
        amount:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/total_amount'
      
    bank_transfer:
      type: object
      properties:
        masked_account_number_last4:
          type: string
          description: The last 4 characters of the local reference for a bank account
            number.
        bank:
          $ref: '#/components/schemas/bank'
      description: Data relating to a bank transfer directly to or from the Payer's bank account.
    
    bank:
      type: object
      properties:
        code:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/bank.code'

    bank_account:
      type: object
      properties:
        name:
          type: string
          description: The name assocaited with the bank account
        identifier_code:
          type: string
          description: The international identifier code for the bank.
        iban:
          type: string
          description: The international identifier of the bank account.
        code:
          type: string
          description: The local identifier of the bank.
        account_number:
          type: string
          description: The local identifier of the bank account.
   
    mandate:
      type: object
      properties:
        code:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/apm.mandate.reference'
    
    filter:
      type: object
      description: Indicates what fields and values used to filter the current list of resource objects in the current response.
    
    paging:
      type: object
      description: The paging values used to generate this response.
      properties:
        page:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.page'
        page_size:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.page_size'
        order_by:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.order_by'
        order:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/pagination.order'
     
    scope:
      type: object
      properties:
        merchant_id:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/merchant_id'
        merchant_name:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/merchant_name'
        accounts:
          $ref: '#/components/schemas/accounts'
    
    accounts:
      type: array
      items:
        type: object
        properties:
          account_id:
            $ref: 'data_dictionary.v1.yaml#/components/schemas/account_id'
          account_name:
            $ref: 'data_dictionary.v1.yaml#/components/schemas/account_name'
          permissions:
            type: array
            items:
              $ref: 'data_dictionary.v1.yaml#/components/schemas/permissions'
    system:
      type: object
      description: Configuration relating to a transactions from the Global Payments system. This info is relevant for troubleshooting and integrators using other Global Payments systems to payment process.
      properties:
        mid:
           $ref: 'data_dictionary.v1.yaml#/components/schemas/system.mid'
        tid:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.tid'
        hierarchy:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.hierarchy'
        name:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.name'
        dba:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/system.dba'

    action:
      type: object
      description: Information about the Action executed.
      properties:
        id:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/id'
        type:
          type: string
          description: Indicates the action taken.
          example: DEPOSIT_LIST
          enum: ##REVISIT##
          - DEPOSIT_LIST
          - DEPOSIT_SINGLE
        time_created:
           $ref: 'data_dictionary.v1.yaml#/components/schemas/time_created'
        result_code:
           $ref: 'data_dictionary.v1.yaml#/components/schemas/result_code'
        app_id:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/app_id'
        app_name:
          $ref: 'data_dictionary.v1.yaml#/components/schemas/app_name'

    notifications:
      type: object
      description: Indicates to Global Payments where the merchant wants to receive notifications of certain events that occur on the Global Payments system.
      properties:
        return_url:
         $ref: data_dictionary.v1.yaml#/components/schemas/notifications.return_url
        
        status_url:
          $ref: data_dictionary.v1.yaml#/components/schemas/notifications.status_url
        
        challenge_return_url:
          $ref: data_dictionary.v1.yaml#/components/schemas/notifications.challenge_return_url
        
        three_ds_method_return_url:
          $ref: data_dictionary.v1.yaml#/components/schemas/notifications.three_ds_method_return_url
        
        decoupled_challenge_return_url:
          $ref: data_dictionary.v1.yaml#/components/schemas/notifications.decoupled_challenge_return_url
      

    notification_post_response:
      type: object
      properties:
        id:
          $ref: data_dictionary.v1.yaml#/components/schemas/id
        time_created:
          $ref: data_dictionary.v1.yaml#/components/schemas/time_created
        type:
          $ref: data_dictionary.v1.yaml#/components/schemas/transaction.type
        status:
          $ref: data_dictionary.v1.yaml#/components/schemas/transaction.status
        channel:
           $ref: data_dictionary.v1.yaml#/components/schemas/transaction.channel
        capture_mode:
           $ref: data_dictionary.v1.yaml#/components/schemas/transaction.capture_mode
        amount:
           $ref: data_dictionary.v1.yaml#/components/schemas/transaction.amount
        currency:
           $ref: data_dictionary.v1.yaml#/components/schemas/transaction.amount
        country:
           $ref: data_dictionary.v1.yaml#/components/schemas/country
        merchant_id:
          $ref: data_dictionary.v1.yaml#/components/schemas/merchant_id
        merchant_name:
          $ref: data_dictionary.v1.yaml#/components/schemas/merchant_name
        account_id:
          $ref: data_dictionary.v1.yaml#/components/schemas/account_id
        account_name:
          $ref: data_dictionary.v1.yaml#/components/schemas/account_name
        
        reference:
          $ref: data_dictionary.v1.yaml#/components/schemas/transaction.reference
                                                                    
        batch_id:
           $ref: data_dictionary.v1.yaml#/components/schemas/batch_id
       
        payment_method:
          $ref: '../Transactions-2020-10-22.v1.yaml#/components/schemas/payment_method_response'
       
        action:
          $ref: schema_objects.v1.yaml#/components/schemas/action
    payment_method_not_response:
      type: object
      properties:
        result:
          $ref: data_dictionary.v1.yaml#/components/schemas/result
        
        message:
          $ref: data_dictionary.v1.yaml#/components/schemas/message

        entry_mode:
          $ref: data_dictionary.v1.yaml#/components/schemas/payment_method.entry_mode

        apm:
          $ref: '#/components/schemas/apm_not_response'
    apm_not_response:
      type: object
      properties:
        provider:
         $ref: data_dictionary.v1.yaml#/components/schemas/apm.provider
        redirect_url:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.redirect_url
        session_token:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.session_token
        fund_status:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.fund_status
        wait_notification:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.wait_notification
        optional_redirect:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.optional_redirect
        provider_transaction_reference:
           $ref: data_dictionary.v1.yaml#/components/schemas/apm.provider_transaction_reference
        provider_time_created:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.provider_time_created
        provider_payer_name:
           $ref: data_dictionary.v1.yaml#/components/schemas/apm.provider_payer_name
       
        payment_description:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.payment_description
        confirmed_accountholder:
          $ref: data_dictionary.v1.yaml#/components/schemas/apm.confirmed_accountholder
        account_number:
          $ref: data_dictionary.v1.yaml#/components/schemas/bank.account_number
        iban:
          $ref: data_dictionary.v1.yaml#/components/schemas/bank.iban
        bank_identifier_code:
          $ref: data_dictionary.v1.yaml#/components/schemas/bank.identifier_code
        bank_name:
          $ref: data_dictionary.v1.yaml#/components/schemas/bank.name
        bank_address:
          $ref: data_dictionary.v1.yaml#/components/schemas/bank_address
       
      description: Data associated with an APM.     



    document:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the document on the Global Payments system
          example: DOC_lskdnfosdfjsdfsdf23dasd
        b64_content:
          type: string
          description: The document represented as a base64 encoded string.
  

    


## Security Section
  securitySchemes:  ## Security Section
    bearerAuth:
      type: http
      scheme: bearer
